"""The registered demo scripts, keyed by their ``--automation-demo`` id.

Bare Command steps must be unambiguous command prefixes ("/copy" would open the
autocomplete menu instead of running — see tests/test_demo_scripts.py).

ids 1/2 are the wide (16:9) demos; ids 3/4 are square (1:1) variants with a few
extra lines to fill the taller window. Recording window size + font/margin per id
live in tools/create_media/fastcalculator.json.
"""

from __future__ import annotations

from automated_screenshot_connector import Command, DemoScript, Pause, Screenshot, TypeText

DEMOS: dict[int, DemoScript] = {
    1: DemoScript(
        id=1,
        name="basic-math",
        steps=(
            Pause(0.5),
            TypeText("1+1\n"),
            Pause(0.6),
            TypeText("5*88\n"),
            Pause(0.6),
            TypeText("100/4\n"),
            Pause(0.6),
            TypeText("12*12\n"),
            Pause(1.1),
            Screenshot("basic-results"),
            Command("/clear"),
            Pause(0.5),
            TypeText("{price} = 20\n"),
            Pause(0.6),
            TypeText("{price} * 3\n"),
            Pause(0.6),
            TypeText("{price} + 5\n"),
            Pause(0.6),
            TypeText("{price} / 4\n"),
            Pause(1.1),
            Screenshot("variables"),
            Pause(1.0),
        ),
    ),
    2: DemoScript(
        id=2,
        name="features",
        steps=(
            Pause(0.5),
            TypeText("100 + 19%\n"),
            Pause(0.6),
            TypeText("10 {times} 5\n"),
            Pause(0.6),
            TypeText("sqrt(144)\n"),
            Pause(0.6),
            TypeText("round(2.7)\n"),
            Pause(0.6),
            TypeText("1000 / 8\n"),
            Pause(1.1),
            Screenshot("features"),
            Pause(1.0),
        ),
    ),
    3: DemoScript(
        id=3,
        name="basic-math-square",
        steps=(
            Pause(0.5),
            TypeText("1+1\n"),
            Pause(0.6),
            TypeText("5*88\n"),
            Pause(0.6),
            TypeText("100/4\n"),
            Pause(0.6),
            TypeText("12*12\n"),
            Pause(0.6),
            TypeText("480/6\n"),
            Pause(0.6),
            TypeText("7*7\n"),
            Pause(0.6),
            TypeText("90-15\n"),
            Pause(1.1),
            Screenshot("basic-results"),
            Command("/clear"),
            Pause(0.5),
            TypeText("{price} = 20\n"),
            Pause(0.6),
            TypeText("{price} * 3\n"),
            Pause(0.6),
            TypeText("{price} + 5\n"),
            Pause(0.6),
            TypeText("{price} / 4\n"),
            Pause(0.6),
            TypeText("{price} - 8\n"),
            Pause(0.6),
            TypeText("{price} * 2\n"),
            Pause(1.1),
            Screenshot("variables"),
            Pause(1.0),
        ),
    ),
    4: DemoScript(
        id=4,
        name="features-square",
        steps=(
            Pause(0.5),
            TypeText("100 + 19%\n"),
            Pause(0.6),
            TypeText("10 {times} 5\n"),
            Pause(0.6),
            TypeText("sqrt(144)\n"),
            Pause(0.6),
            TypeText("round(2.7)\n"),
            Pause(0.6),
            TypeText("max(4, 8)\n"),
            Pause(0.6),
            TypeText("abs(-7)\n"),
            Pause(0.6),
            TypeText("floor(9.7)\n"),
            Pause(0.6),
            TypeText("log(1000)\n"),
            Pause(0.6),
            TypeText("1000 / 8\n"),
            Pause(1.1),
            Screenshot("features"),
            Pause(1.0),
        ),
    ),
}
